### ISSUE TITLE
Support direct EFX deposit from BSC

### ISSUE THREAD

**Issue by jeisses** [effectai/force-frontend#151]
## Feature

Users should be able to deposit EFX into their Effect vaccount directly from BSC

## Background

Currently users use the platform using a BSC-vaccount and MetaMask which allows them to earn vEFX. This EFX can be easily withdrawn to their BSC account.

This does not work the other way around: to deposit BSC-EFX to their vaccount they must go through an EOS account. This is very inconvenient because BSC users often don't have access to an EOS account with resources

**Comment by MiggySmallz** [comment]
This is a bit confusing for me. What would the purpose of this be? If a user is already using BSC and metamask on the platform wouldn't they only want to withdraw and have no need to deposit into the vaccount? Can you explain the use case a bit more please :)

**Comment by jeisses** [comment]
This is meant for BSC users holding EFX that want to post tasks (as
requesters). For example, if you order on https://socials.effect.network
using Metamask you will need vEFX, which you can only deposit from a EOS
account

The bridge recently started supporting EOS memos on transactions. I
think @David
Britt ***@***.***> already started looking into this

**Comment by djmbritt** [comment]
These are the methods that were implemented.
As you can see there is smart contract method and a js method that we can use in effect-js

- https://github.com/provable-things/ptokens-erc777-smart-contract/blob/e7a6c2421ab0efb94fec40368cef9cd5d970435a/lib/peg-out.js
- https://github.com/provable-things/ptokens-peos-on-eth-smart-contract/blob/f18cc7193b0fba0351304fa108d77bdb1842b616/contracts/PEosOnEthVault.cpp#L18

**Comment by jeisses** [comment]
@djmbritt in the code you linked it does not seem possible to add a memo for `pegOut` (the pegOut happens when you turn pEFX on BSC to "real" EFX on EOS).

Without a memo it's not possible to do a vAccount deposit. 

Did you find anything in pTokens which would make that possible?

**Comment by djmbritt** [comment]
https://github.com/provable-things/ptokens.js-v1/issues/9
