### ISSUE TITLE
Explicit Warning That All Tasks and their Results are stored on IPFS

### ISSUE THREAD

**Issue by djstrikanova** [effectai/force-frontend#195]
I think we should make it clear to users that the tasks they post on Effect Network through the Front End or the SDK by default are going to be publicly available for anyone to access. The same for the results, unless they mask results by providing their own servers to complete the tasks in the task context.

**Comment by laurensV** [comment]
Good point, we should add this message (e.g. "This task will be posted on the blockchain and the data will be stored publicly on IPFS").

Maybe we should also think about providing easier ways to provide requesters with the option to have private task data (e.g. only allowing workers with a qualification access to your tasks or maybe even better: only give access to the task of the worker that currently has a reservation for that task)

**Comment by djstrikanova** [comment]
That message is good. I think making it easier for more private tasks with Effect Network just being a gateway to pay workers would help. I imagine there is no real good way to provide privacy unless Effect Network is just used as an authentication and payment gateway for workers with all the tasks completion process done externally embedded in some iframe. Basically, once the task is done they get a completion code which they can submit for the tasks hosted on Effect Network. Something to consider once enhancements to validation and qualifications are done.
