### ISSUE TITLE
Show user qualification values

### ISSUE THREAD

**Issue by jeisses** [effectai/force-frontend#196]
On the qualifications page on the user profile, show the values that belongs to the quali.

Currently we only show the qualifications icon if the user has it. 

Qualifications now also have `value` property in the `userquali` table, this should be displayed as well.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by jeisses** [comment]
Sure, let me know if you need help to get started
