### ISSUE TITLE
Assign selection of default qualifcations to campaigns

### ISSUE THREAD

**Issue by jeisses** [effectai/force-frontend#229]
When creating a campaign the frontend should have a few qualifications selected by default, such as Human (include) and Blocked (exclude)

The qualification IDs that are automatically selected should be listed in the config and can be different pet network

**Comment by rochelle8044** [comment]
I agree. It also MUST have qualification #137, "Bad Actor", as a standard 'exclude' as well. This is basically a global ban for worker accounts identified that massively scammed tasks.
