### ISSUE TITLE
Show user balance in the header

### ISSUE THREAD

**Issue by jeisses** [effectai/force-frontend#241]
The user balance of EFX tokens should be shown in the navbar converted to USD. It should include the value of pending payouts (potentially the pending payouts can be shown with a + prefix, like `$1.40 (+ $0.90)`. Clicking on the balance should bring you to your profile

![Image](https://github.com/effectai/force-frontend/assets/1128863/5edf67ca-c7bc-4fd0-8f66-3fc698825540)

**Comment by jasonttian** [comment]
I'm interested in this task.
Could I take this?

**Comment by Jeffrieh** [comment]
> I'm interested in this task. Could I take this?

Sorry for the late reply, you can pick up this issue if you want!

you can use the `useEfxPrice` hook inside of the `UseEffectClient` for this :)
