### ISSUE TITLE
Stuck at "Loading Task Data" screen after reserving second task

### ISSUE THREAD

**Issue by jeisses** [effectai/force-frontend#253]
After I submit a task, and then reserve the next one, I'm getting stuck at the "Loading Task Data" screen.

When I submit the "reservetask" transaction, for a second the old template flashes, and then the loading screen below appears and stays (no console errors or network requests are stuck):

![image](https://github.com/effectai/force-frontend/assets/1128863/e8e598ff-7dfe-4ed1-861a-b4786f655812)

When I refresh the page the task loads correctly. But when I submit, then reserve, this happens again.

I can consistently reproduce this

Browser: Firefox 126.0.3, Linux x86_64

**Comment by Jeffrieh** [comment]
Should be fixed
